// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Deterministic AST codemod over the raw Plato-generated TypeScript
// (tools/plato/clash_math.plato -> plato.g.ts). It removes the Number/Boolean
// prototype pollution and the allocation-free scalar dispatch overhead by:
//
//   a. rewriting scalar method calls to native operators
//      (.Add -> +, .Subtract -> -, .Multiply -> *, .Divide -> /, .Modulo -> %,
//       .Negative() -> unary -, .LessThan -> <, .GreaterThan -> >,
//       .LessThanOrEquals -> <=, .GreaterThanOrEquals -> >=, .Sqrt() ->
//       Math.sqrt, .Abs() -> Math.abs, .Floor() -> Math.floor, .Pow -> **,
//       .And -> &&, .Or -> ||, .Not() -> !), every result parenthesised;
//   b. hoisting the Number-helper functions installed on the prototype
//      (FoldMin, FoldMax, Min2, Max2, OverlapStep, ClampedLo, ClampedHi) into a
//      module-scoped `Scalars` namespace, lifting each body mechanically from
//      its Intrinsics.Install call (this -> a `self` first parameter, then rule
//      a on the lifted body), and rewriting recv.Fn(args) -> Scalars.Fn(recv,
//      args);
//   c. deleting all Intrinsics.Install statements, the Install helper and the
//      `declare global` blocks, so the output has zero "prototype" / "declare
//      global";
//   d. printing deterministically through the TypeScript printer, so the
//      transform is idempotent (running it on its own output is a no-op).
//
// Name-based rewriting is safe only because, after the Vec3.Plus rename, no
// generated class method shares a scalar-intrinsic name; the codemod asserts
// this by scanning class declarations first and throwing on any collision.
//
// Usage: node tools/plato/scalar-codemod.mjs <input.ts> <output.ts>
//        node tools/plato/scalar-codemod.mjs <input.ts>            (stdout)

import ts from 'typescript';
import { readFileSync, writeFileSync } from 'node:fs';
import { appendFlattened } from './flatten-codemod.mjs';

// Scalar operator method name -> native binary operator token.
const SCALAR_BINARY = new Map([
  ['Add', ts.SyntaxKind.PlusToken],
  ['Subtract', ts.SyntaxKind.MinusToken],
  ['Multiply', ts.SyntaxKind.AsteriskToken],
  ['Divide', ts.SyntaxKind.SlashToken],
  ['Modulo', ts.SyntaxKind.PercentToken],
  ['LessThan', ts.SyntaxKind.LessThanToken],
  ['GreaterThan', ts.SyntaxKind.GreaterThanToken],
  ['LessThanOrEquals', ts.SyntaxKind.LessThanEqualsToken],
  ['GreaterThanOrEquals', ts.SyntaxKind.GreaterThanEqualsToken],
  ['Pow', ts.SyntaxKind.AsteriskAsteriskToken],
  ['And', ts.SyntaxKind.AmpersandAmpersandToken],
  ['Or', ts.SyntaxKind.BarBarToken],
]);
// Scalar method name -> Math.<fn> unary call.
const SCALAR_MATHFN = new Map([
  ['Sqrt', 'sqrt'],
  ['Abs', 'abs'],
  ['Floor', 'floor'],
]);
// Scalar prefix-unary operators.
const SCALAR_UNARY = new Set(['Negative', 'Not']);

const SCALAR_OP_NAMES = new Set([
  ...SCALAR_BINARY.keys(),
  ...SCALAR_MATHFN.keys(),
  ...SCALAR_UNARY,
]);

const HEADER = [
  '// This Source Code Form is subject to the terms of the Mozilla Public',
  '// License, v. 2.0. If a copy of the MPL was not distributed with this',
  '// file, You can obtain one at https://mozilla.org/MPL/2.0/.',
  '// Autogenerated from tools/plato/clash_math.plato - DO NOT EDIT (see tools/plato/README.md)',
  '/* eslint-disable */',
  '// noinspection JSUnusedGlobalSymbols',
  '',
  '',
].join('\n');

/** True for an `Intrinsics.Install(...)` expression statement. */
function isInstallStatement(node) {
  if (!ts.isExpressionStatement(node)) return false;
  const call = node.expression;
  if (!ts.isCallExpression(call)) return false;
  const callee = call.expression;
  return (
    ts.isPropertyAccessExpression(callee) &&
    ts.isIdentifier(callee.expression) &&
    callee.expression.text === 'Intrinsics' &&
    callee.name.text === 'Install'
  );
}

/** True for a `declare global { ... }` augmentation block. */
function isDeclareGlobal(node) {
  return ts.isModuleDeclaration(node) && (node.flags & ts.NodeFlags.GlobalAugmentation) !== 0;
}

/** True for the `Intrinsics` namespace declaration. */
function isIntrinsicsNamespace(node) {
  return (
    ts.isModuleDeclaration(node) &&
    ts.isIdentifier(node.name) &&
    node.name.text === 'Intrinsics'
  );
}

/** Collect every method name used as `recv.Name(...)` anywhere in the tree. */
function collectCalledNames(root) {
  const names = new Set();
  const walk = (n) => {
    if (ts.isCallExpression(n) && ts.isPropertyAccessExpression(n.expression)) {
      names.add(n.expression.name.text);
    }
    ts.forEachChild(n, walk);
  };
  walk(root);
  return names;
}

export function transform(sourceText, fileName = 'plato.g.ts') {
  const sourceFile = ts.createSourceFile(
    fileName,
    sourceText,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true,
    ts.ScriptKind.TS,
  );

  const transformer = (context) => {
    const { factory } = context;

    // --- rule a + rule b: rewrite scalar/helper method calls (post-order) ---
    let helperNames = new Set();
    const visitExpr = (node) => {
      node = ts.visitEachChild(node, visitExpr, context);
      if (ts.isCallExpression(node) && ts.isPropertyAccessExpression(node.expression)) {
        const name = node.expression.name.text;
        const recv = node.expression.expression;
        const args = node.arguments;
        const binary = SCALAR_BINARY.get(name);
        if (binary !== undefined) {
          assertArgc(name, args, 1);
          return factory.createParenthesizedExpression(
            factory.createBinaryExpression(recv, binary, args[0]),
          );
        }
        if (name === 'Negative') {
          assertArgc(name, args, 0);
          return factory.createParenthesizedExpression(
            factory.createPrefixUnaryExpression(ts.SyntaxKind.MinusToken, recv),
          );
        }
        if (name === 'Not') {
          assertArgc(name, args, 0);
          return factory.createPrefixUnaryExpression(
            ts.SyntaxKind.ExclamationToken,
            factory.createParenthesizedExpression(recv),
          );
        }
        const mathFn = SCALAR_MATHFN.get(name);
        if (mathFn !== undefined) {
          assertArgc(name, args, 0);
          return factory.createCallExpression(
            factory.createPropertyAccessExpression(factory.createIdentifier('Math'), mathFn),
            undefined,
            [recv],
          );
        }
        if (helperNames.has(name)) {
          return factory.createCallExpression(
            factory.createPropertyAccessExpression(factory.createIdentifier('Scalars'), name),
            undefined,
            [recv, ...args],
          );
        }
      }
      return node;
    };

    // Replace `this` with the lifted `self` parameter inside a helper body.
    const substThis = (node) => {
      if (node.kind === ts.SyntaxKind.ThisKeyword) return factory.createIdentifier('self');
      return ts.visitEachChild(node, substThis, context);
    };

    const numberType = () => factory.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword);

    // Lift one installed helper into an exported Scalars function.
    const liftHelper = ({ name, fnExpr }) => {
      if (!ts.isFunctionExpression(fnExpr) && !ts.isArrowFunction(fnExpr)) {
        throw new Error(`Install for '${name}' is not a function expression`);
      }
      const realParams = fnExpr.parameters.slice(1); // drop the `this` parameter
      const params = [
        factory.createParameterDeclaration(undefined, undefined, 'self', undefined, numberType()),
        ...realParams.map((p) =>
          factory.createParameterDeclaration(
            undefined,
            undefined,
            p.name.getText(sourceFile),
            undefined,
            numberType(),
          ),
        ),
      ];
      const body = visitExpr(substThis(fnExpr.body));
      return factory.createFunctionDeclaration(
        [factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        undefined,
        name,
        undefined,
        params,
        numberType(),
        body,
      );
    };

    return (root) => {
      if (!ts.isSourceFile(root)) return root;

      // --- collision guard: no class method shares a rewrite-target name ---
      const calledNames = collectCalledNames(root);
      const installStatements = root.statements.filter(isInstallStatement);
      const helpers = [];
      for (const stmt of installStatements) {
        const call = stmt.expression;
        const nameArg = call.arguments[1];
        if (!nameArg || !ts.isStringLiteralLike(nameArg)) continue;
        const name = nameArg.text;
        if (SCALAR_OP_NAMES.has(name)) continue; // native-operator scalar op
        if (!calledNames.has(name)) continue; // installed but unused (e.g. Compare)
        helpers.push({ name, fnExpr: call.arguments[2] });
      }
      helperNames = new Set(helpers.map((h) => h.name));

      for (const stmt of root.statements) {
        if (!ts.isClassDeclaration(stmt)) continue;
        for (const member of stmt.members) {
          const memberName =
            member.name && ts.isIdentifier(member.name) ? member.name.text : undefined;
          if (memberName && (SCALAR_OP_NAMES.has(memberName) || helperNames.has(memberName))) {
            throw new Error(
              `Name collision: class ${stmt.name?.text ?? '<anon>'} defines method ` +
                `'${memberName}', which is also a scalar/helper rewrite target. ` +
                'Name-based rewriting is unsafe; rename in the .plato source.',
            );
          }
        }
      }

      const scalarsNamespace =
        helpers.length > 0
          ? factory.createModuleDeclaration(
              undefined,
              factory.createIdentifier('Scalars'),
              factory.createModuleBlock(helpers.map(liftHelper)),
              ts.NodeFlags.Namespace,
            )
          : null;

      const out = [];
      for (const stmt of root.statements) {
        if (isDeclareGlobal(stmt)) continue; // rule c
        if (isInstallStatement(stmt)) continue; // rule c
        if (isIntrinsicsNamespace(stmt) && stmt.body && ts.isModuleBlock(stmt.body)) {
          const kept = stmt.body.statements.filter(
            (s) => !(ts.isFunctionDeclaration(s) && s.name && s.name.text === 'Install'),
          );
          out.push(
            factory.updateModuleDeclaration(
              stmt,
              stmt.modifiers,
              stmt.name,
              factory.updateModuleBlock(stmt.body, kept),
            ),
          );
          if (scalarsNamespace) out.push(scalarsNamespace); // rule b: hoisted helpers
          continue;
        }
        out.push(visitExpr(stmt)); // rule a inside class/other declarations
      }

      return factory.updateSourceFile(root, out);
    };
  };

  const result = ts.transform(sourceFile, [transformer]);
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: true,
  });
  const printed = printer.printFile(result.transformed[0]);
  result.dispose();

  // Phase 2: append the flattened tuple kernels (see flatten-codemod.mjs).
  const output = appendFlattened(HEADER + printed.replace(/\s*$/, '') + '\n', fileName);

  // rule c invariant: fail loudly if any pollution survived.
  if (output.includes('prototype')) {
    throw new Error("codemod invariant violated: output still contains 'prototype'");
  }
  if (output.includes('declare global')) {
    throw new Error("codemod invariant violated: output still contains 'declare global'");
  }
  return output;
}

function assertArgc(name, args, expected) {
  if (args.length !== expected) {
    throw new Error(`scalar op ${name} expected ${expected} args, got ${args.length}`);
  }
}

// --- CLI ---
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3];
  if (!inputPath) {
    console.error('usage: node scalar-codemod.mjs <input.ts> [output.ts]');
    process.exit(2);
  }
  const source = readFileSync(inputPath, 'utf8');
  const out = transform(source, inputPath.split('/').pop());
  if (outputPath) {
    writeFileSync(outputPath, out);
  } else {
    process.stdout.write(out);
  }
}
