/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import '@/test/setup-dom.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import * as echarts from 'echarts';
import type { ChartSelectEvent } from './useEChart.js';
import { engineDataIndex, rawIndexResolver, selectionFromEChartEvent } from './useEChart.js';

describe('chart click replacement selection (#4832)', () => {
  it('replaces A with B from the events generated by a real ECharts click path', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const emitted: ChartSelectEvent[] = [];
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      xAxis: { type: 'category', data: ['A', 'B'] },
      yAxis: { type: 'value' },
      series: [{ type: 'bar', selectedMode: 'multiple', data: [1, 2] }],
    });
    chart.on('selectchanged', (rawEvent) => {
      const event = rawEvent as Parameters<typeof selectionFromEChartEvent>[0];
      rawEvents.push(event);
      emitted.push(selectionFromEChartEvent(event));
    });

    try {
      const internals = chart as unknown as {
        getModel: () => {
          getSeriesByIndex: (index: number) => {
            getData: () => { getItemGraphicEl: (index: number) => object | undefined };
          };
        };
      };
      const series = internals.getModel().getSeriesByIndex(0);
      const first = series.getData().getItemGraphicEl(0);
      const second = series.getData().getItemGraphicEl(1);
      assert.ok(first);
      assert.ok(second);
      chart.getZr().trigger('click', { target: first, topTarget: first });
      chart.getZr().trigger('click', { target: second, topTarget: second });

      assert.deepEqual(emitted, [
        { items: [{ seriesIndex: 0, dataIndex: 0 }] },
        { items: [{ seriesIndex: 0, dataIndex: 1 }] },
      ]);
      assert.deepEqual(rawEvents[1]?.selected, [{ seriesIndex: 0, dataIndex: [0, 1] }]);
      assert.equal(rawEvents[1]?.fromActionPayload?.dataIndexInside, 1);
      assert.equal(rawEvents[1]?.fromActionPayload?.dataIndex, undefined);
    } finally {
      chart.dispose();
    }
  });

  it('maps a real legend-filtered internal click index back to the raw bucket (#4832)', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const emitted: ChartSelectEvent[] = [];
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      legend: { data: ['A', 'B'], selected: { A: false, B: true } },
      series: [{
        type: 'pie',
        selectedMode: 'multiple',
        data: [{ name: 'A', value: 1 }, { name: 'B', value: 2 }],
      }],
    });
    const internals = chart as unknown as {
      getModel: () => {
        getSeriesByIndex: (index: number) => {
          getData: () => {
            getItemGraphicEl: (index: number) => object | undefined;
            getRawIndex: (index: number) => number;
          };
        };
      };
    };
    const rawIndex = rawIndexResolver(chart);
    chart.on('selectchanged', (rawEvent) => {
      const event = rawEvent as Parameters<typeof selectionFromEChartEvent>[0];
      rawEvents.push(event);
      emitted.push(selectionFromEChartEvent(event, rawIndex));
    });

    try {
      const series = internals.getModel().getSeriesByIndex(0);
      const visibleB = series.getData().getItemGraphicEl(0);
      assert.ok(visibleB, 'legend filtering leaves B at internal index zero');
      assert.equal(series.getData().getRawIndex(0), 1);
      chart.getZr().trigger('click', { target: visibleB, topTarget: visibleB });

      assert.equal(rawEvents[0]?.fromActionPayload?.dataIndexInside, 0);
      assert.deepEqual(rawEvents[0]?.selected, [{ seriesIndex: 0, dataIndex: [1] }]);
      assert.deepEqual(emitted, [{ items: [{ seriesIndex: 0, dataIndex: 1 }] }]);
    } finally {
      chart.dispose();
    }
  });

  it('removes the real treemap virtual-root offset for its first and last buckets (#4832)', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const emitted: ChartSelectEvent[] = [];
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      series: [{
        type: 'treemap',
        selectedMode: 'multiple',
        data: [
          { name: 'A', value: 3 },
          { name: 'B', value: 2 },
          { name: 'C', value: 1 },
        ],
      }],
    });
    const internals = chart as unknown as {
      getModel: () => {
        getSeriesByIndex: (index: number) => {
          getData: () => {
            getItemGraphicEl: (index: number) => object | undefined;
            getRawIndex: (index: number) => number;
          };
        };
      };
    };
    const rawIndex = rawIndexResolver(chart);
    chart.on('selectchanged', (rawEvent) => {
      const event = rawEvent as Parameters<typeof selectionFromEChartEvent>[0];
      rawEvents.push(event);
      emitted.push(selectionFromEChartEvent(event, rawIndex));
    });

    try {
      const data = internals.getModel().getSeriesByIndex(0).getData();
      const first = data.getItemGraphicEl(1);
      const last = data.getItemGraphicEl(3);
      assert.ok(first);
      assert.ok(last);
      assert.equal(data.getRawIndex(0), 0, 'the virtual root occupies raw index zero');
      assert.equal(data.getRawIndex(1), 1);
      assert.equal(data.getRawIndex(3), 3);
      chart.getZr().trigger('click', { target: first, topTarget: first });
      chart.getZr().trigger('click', { target: last, topTarget: last });

      assert.equal(rawEvents[0]?.fromActionPayload?.dataIndexInside, 1);
      assert.equal(rawEvents[1]?.fromActionPayload?.dataIndexInside, 3);
      assert.deepEqual(emitted, [
        { items: [{ seriesIndex: 0, dataIndex: 0 }] },
        { items: [{ seriesIndex: 0, dataIndex: 2 }] },
      ]);
    } finally {
      chart.dispose();
    }
  });

  it('applies the inverse treemap offset when feedback highlights first and last buckets (#4832)', async () => {
    const host = document.createElement('div');
    document.body.appendChild(host);
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    chart.setOption({
      animation: false,
      series: [{ type: 'treemap', emphasis: { focus: 'self' }, data: [{ name: 'A', value: 3 }, { name: 'B', value: 2 }, { name: 'C', value: 1 }] }],
    });
    const internals = chart as unknown as {
      getModel: () => { getSeriesByIndex: (index: number) => { getData: () => { getItemGraphicEl: (index: number) => { childrenRef?: () => Array<{ currentStates?: string[] }> } } } };
    };
    const highlighted: number[] = [];
    chart.on('highlight', (event) => { highlighted.push((event as { dataIndex: number }).dataIndex); });
    try {
      const data = internals.getModel().getSeriesByIndex(0).getData();
      chart.dispatchAction({ type: 'highlight', seriesIndex: 0, dataIndex: engineDataIndex(chart, { seriesIndex: 0, dataIndex: 0 }) });
      await new Promise((resolve) => setTimeout(resolve, 0));
      chart.resize();
      chart.getZr().flush();
      assert.equal(highlighted.at(-1), 1, 'first aggregation bucket maps past the virtual root');
      assert.ok(data.getItemGraphicEl(1).childrenRef?.().some(({ currentStates }) => currentStates?.includes('emphasis')));
      assert.ok(!data.getItemGraphicEl(3).childrenRef?.().some(({ currentStates }) => currentStates?.includes('emphasis')));
      chart.dispatchAction({ type: 'downplay' });
      chart.dispatchAction({ type: 'highlight', seriesIndex: 0, dataIndex: engineDataIndex(chart, { seriesIndex: 0, dataIndex: 2 }) });
      await new Promise((resolve) => setTimeout(resolve, 0));
      chart.resize();
      chart.getZr().flush();
      assert.equal(highlighted.at(-1), 3, 'last aggregation bucket maps to the last real treemap node');
      assert.ok(!data.getItemGraphicEl(1).childrenRef?.().some(({ currentStates }) => currentStates?.includes('emphasis')));
      assert.ok(data.getItemGraphicEl(3).childrenRef?.().some(({ currentStates }) => currentStates?.includes('emphasis')));
    } finally {
      chart.dispose();
      host.remove();
    }
  });

  it('selects a feedback-selected bucket instead of clearing the other chart source (#4832)', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      xAxis: { type: 'category', data: ['Level 1', 'Level 2'] },
      yAxis: { type: 'value' },
      series: [{
        type: 'bar',
        selectedMode: 'multiple',
        data: [{ value: 1, selected: true }, { value: 1, selected: true }],
      }],
    });
    chart.on('selectchanged', (rawEvent) => { rawEvents.push(rawEvent as Parameters<typeof selectionFromEChartEvent>[0]); });

    try {
      const internals = chart as unknown as {
        getModel: () => { getSeriesByIndex: (index: number) => { getData: () => { getItemGraphicEl: (index: number) => object | undefined } } };
      };
      const level1 = internals.getModel().getSeriesByIndex(0).getData().getItemGraphicEl(0);
      assert.ok(level1);
      chart.getZr().trigger('click', { target: level1, topTarget: level1 });

      const raw = rawEvents[0];
      assert.equal(raw?.fromAction, 'unselect', 'ECharts toggles the feedback-selected mark off');
      assert.deepEqual(selectionFromEChartEvent(raw!, undefined, false), {
        items: [{ seriesIndex: 0, dataIndex: 0 }],
      }, 'a feedback mark becomes a replacement selection');
      assert.deepEqual(selectionFromEChartEvent(raw!, undefined, true), { items: [] }, 'the active source can still deselect itself');
    } finally {
      chart.dispose();
    }
  });

  it('clears selection when the current bucket is unselected', () => {
    assert.deepEqual(selectionFromEChartEvent({
      fromAction: 'toggleSelected',
      fromActionPayload: { seriesIndex: 0, dataIndex: 1 },
      selected: [],
    }), { items: [] });
  });

  it('retains cumulative fallback semantics for non-click actions without a payload', () => {
    assert.deepEqual(selectionFromEChartEvent({
      selected: [
        { seriesIndex: 0, dataIndex: [2] },
        { seriesIndex: 1, dataIndex: [3] },
      ],
    }), { items: [
      { seriesIndex: 0, dataIndex: 2 },
      { seriesIndex: 1, dataIndex: 3 },
    ] });
  });
});
