/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import '@/test/setup-dom.js';
import { afterEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { EVENT_SHOW_SHORTCUTS } from '@/lib/tours/events';
import { useViewerStore } from '@/store';
import { buildCoreCommands } from './commandPaletteCommandsCore.js';
import { buildPanelCommands } from './commandPaletteCommandsPanels.js';
import type { CommandPaletteBuildParams } from './commandPaletteCommandsTypes.js';
import { SURFACE_COMMANDS } from './surface-commands.js';

const WORKSPACE_IDS = [
  'extensions:author', 'extensions:flavors',
  'sidebar:toggle', 'sidebar:collapse', 'sidebar:customize', 'sidebar:reset',
  'schedule:generate', 'schedule:toggle-animation', 'schedule:reset',
  'pref:theme', 'pref:tooltips', 'pref:settings', 'learn:hub',
] as const;

function params(overrides: Partial<CommandPaletteBuildParams> = {}): CommandPaletteBuildParams {
  return {
    execute: () => {}, recentFiles: [], cachedNames: { current: new Set<string>() },
    extensionCommands: [], extensionHost: null, canEditInSession: true,
    cesiumAvailable: false, activateRightPanel: () => {}, activateBottomPanel: () => {},
    runExport: () => {}, ...overrides,
  };
}

afterEach(() => {
  useViewerStore.setState({
    sidebarMode: 'expanded', sidebarCustomizing: false, ganttPanelVisible: false,
    generateScheduleDialogOpen: false, animationEnabled: false,
    ideasOpenEmptyPlan: false, extensionsRequestedView: null,
  });
});

describe('static workspace commands use the shared table (#5870)', () => {
  it('generates each row once in its original palette order with registry metadata', () => {
    const definitions = SURFACE_COMMANDS.filter((command) => WORKSPACE_IDS.some((id) => id === command.id));
    assert.deepEqual(definitions.map((command) => command.id), WORKSPACE_IDS);
    for (const command of definitions) {
      const alsoRibbon = command.id === 'pref:tooltips' || command.id === 'pref:settings';
      assert.deepEqual(command.surfaces, alsoRibbon ? ['palette', 'ribbon'] : ['palette'],
        `${command.id} is available on its declared surfaces`);
    }

    const rows = buildPanelCommands(params()).filter((command) => WORKSPACE_IDS.some((id) => id === command.id));
    assert.deepEqual(rows.map((command) => command.id), WORKSPACE_IDS);
    for (const row of rows) {
      const definition = definitions.find((command) => command.id === row.id);
      assert.ok(definition);
      assert.equal(row.labelKey, definition.labelKey);
      assert.equal(row.icon, definition.icon);
      assert.equal(row.shortcut, 'shortcut' in definition ? definition.shortcut : undefined);
    }
    assert.equal(rows.find((row) => row.id === 'extensions:flavors')?.label, 'Manage flavors…',
      'the old search phrase stays hidden while the visible name follows the catalogue');
    const core = buildCoreCommands(params());
    assert.ok(core.some((command) => command.id === 'model:reposition'),
      'the existing model reposition Tools row remains in the core category');
    assert.ok(core.every((command) => !WORKSPACE_IDS.some((id) => id === command.id)),
      'Tools and Visibility category rows must not also be generated by the core builder');
  });

  it('runs extension, sidebar, schedule, and help actions against their real owners', () => {
    let activatedRight = '';
    let activatedBottom = '';
    const rows = buildPanelCommands(params({
      activateRightPanel: (panel) => { activatedRight = panel; },
      activateBottomPanel: (panel) => { activatedBottom = panel; },
    }));
    const run = (id: string) => {
      const command = rows.find((row) => row.id === id);
      assert.ok(command, `missing ${id}`);
      command.action();
    };

    run('extensions:author');
    assert.equal(activatedRight, 'extensions');
    assert.equal(useViewerStore.getState().extensionsRequestedView, 'ideas');
    assert.equal(useViewerStore.getState().ideasOpenEmptyPlan, true);

    run('sidebar:collapse');
    assert.equal(useViewerStore.getState().sidebarMode, 'collapsed');
    run('sidebar:customize');
    assert.equal(useViewerStore.getState().sidebarMode, 'expanded');
    assert.equal(useViewerStore.getState().sidebarCustomizing, true);

    run('schedule:generate');
    assert.equal(activatedBottom, 'gantt');
    assert.equal(useViewerStore.getState().generateScheduleDialogOpen, true);
    run('schedule:toggle-animation');
    assert.equal(useViewerStore.getState().animationEnabled, true);
    run('schedule:reset');
    assert.equal(useViewerStore.getState().animationEnabled, false);

    let requestedTab = '';
    const onHelp = (event: Event) => { requestedTab = (event as CustomEvent<{ tab: string }>).detail.tab; };
    window.addEventListener(EVENT_SHOW_SHORTCUTS, onHelp);
    try { run('learn:hub'); } finally { window.removeEventListener(EVENT_SHOW_SHORTCUTS, onHelp); }
    assert.equal(requestedTab, 'learn');
  });
});
