/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Rust Code Generator
 *
 * Generates Rust types from EXPRESS schema for:
 * - Type IDs (CRC32 constants)
 * - IfcType enum with all variants
 * - Geometry category classification
 * - Type conversion functions
 */

import type { ExpressSchema, EntityDefinition } from './express-parser.js';
import { crc32, formatCRC32TableLiteral } from './crc32.js';
import { getInheritanceChain } from './express-parser.js';
import { generateSchemaQueries } from './rust-schema-queries.js';

export interface RustGeneratedCode {
  typeIds: string;
  schema: string;
}

/**
 * Generate all Rust code from EXPRESS schema
 */
export function generateRust(schema: ExpressSchema): RustGeneratedCode {
  return {
    typeIds: generateTypeIdConstants(schema),
    schema: generateIfcTypeEnum(schema),
  };
}

/**
 * Generate CRC32 type ID constants
 */
function generateTypeIdConstants(schema: ExpressSchema): string {
  let code = `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Auto-generated IFC Type ID Constants
//!
//! CRC32 hashes for fast type identification.
//! Generated from EXPRESS schema: ${schema.name}
//!
//! DO NOT EDIT - This file is auto-generated by @ifc-lite/codegen

#![allow(dead_code)]

`;

  // Group by category for readability
  const categories = categorizeEntities(schema);

  for (const [category, entities] of Object.entries(categories)) {
    code += `// ${category}\n`;
    for (const entity of entities) {
      const id = crc32(entity.name);
      code += `pub const ${entity.name.toUpperCase()}: u32 = ${id};\n`;
    }
    code += '\n';
  }

  return code;
}

/**
 * Generate the main IfcType enum
 */
function generateIfcTypeEnum(schema: ExpressSchema): string {
  let code = `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Auto-generated IFC Type Enum
//!
//! Generated from EXPRESS schema: ${schema.name}
//!
//! DO NOT EDIT - This file is auto-generated by @ifc-lite/codegen

use std::fmt;

/// IFC Entity Types
///
/// All ${schema.entities.length} entity types from the ${schema.name} schema.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IfcType {
`;

  // Group entities by category
  const categories = categorizeEntities(schema);

  for (const [category, entities] of Object.entries(categories)) {
    code += `    // ${category}\n`;
    for (const entity of entities) {
      if (entity.isAbstract) {
        code += `    /// Abstract entity\n`;
      }
      code += `    ${entity.name},\n`;
    }
    code += '\n';
  }

  // Add Unknown variant for unrecognized types
  code += `    /// Unknown/unrecognized IFC type (stores CRC32 hash)
    Unknown(u32),
}

impl IfcType {
    /// Parse IFC type from string (case-insensitive)
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(s: &str) -> Self {
        let upper = s.to_uppercase();
        match upper.as_str() {
`;

  // Generate match arms for all entities
  for (const entity of schema.entities) {
    code += `            "${entity.name.toUpperCase()}" => Self::${entity.name},\n`;
  }

  code += `            _ => Self::Unknown(crc32_hash(&upper)),
        }
    }

    /// Parse from CRC32 type ID
    pub fn from_id(id: u32) -> Self {
        match id {
`;

  // Generate match arms for CRC32 IDs
  for (const entity of schema.entities) {
    const id = crc32(entity.name);
    code += `            ${id} => Self::${entity.name},\n`;
  }

  code += `            _ => Self::Unknown(id),
        }
    }

    /// Get CRC32 type ID
    pub fn id(&self) -> u32 {
        match self {
`;

  for (const entity of schema.entities) {
    const id = crc32(entity.name);
    code += `            Self::${entity.name} => ${id},\n`;
  }

  code += `            Self::Unknown(id) => *id,
        }
    }

    /// Get string representation (uppercase)
    pub fn as_str(&self) -> &'static str {
        match self {
`;

  for (const entity of schema.entities) {
    code += `            Self::${entity.name} => "${entity.name.toUpperCase()}",\n`;
  }

  code += `            Self::Unknown(_) => "UNKNOWN",
        }
    }

    /// Get display name (PascalCase)
    pub fn name(&self) -> &'static str {
        match self {
`;

  for (const entity of schema.entities) {
    code += `            Self::${entity.name} => "${entity.name}",\n`;
  }

  code += `            Self::Unknown(_) => "Unknown",
        }
    }

    /// Get parent type (if any)
    pub fn parent(&self) -> Option<Self> {
        match self {
`;

  for (const entity of schema.entities) {
    if (entity.supertype) {
      code += `            Self::${entity.name} => Some(Self::${entity.supertype}),\n`;
    }
  }

  code += `            _ => None,
        }
    }

    /// Check if this type is a subtype of another
    pub fn is_subtype_of(&self, parent: Self) -> bool {
        let mut current = Some(*self);
        while let Some(t) = current {
            if t == parent {
                return true;
            }
            current = t.parent();
        }
        false
    }

    /// Check if this is an abstract type
    #[allow(clippy::match_like_matches_macro)]
    pub fn is_abstract(&self) -> bool {
        match self {
`;

  const abstractTypes = schema.entities.filter((e) => e.isAbstract);
  for (const entity of abstractTypes) {
    code += `            Self::${entity.name} => true,\n`;
  }

  code += `            _ => false,
        }
    }

${generateSchemaQueries(schema)}impl fmt::Display for IfcType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

/// CRC32 hash function for unknown types
fn crc32_hash(s: &str) -> u32 {
    const TABLE: [u32; 256] = [
${formatCRC32TableLiteral('        ')}
    ];

    let mut crc = 0xffffffffu32;
    for byte in s.bytes() {
        crc = TABLE[((crc ^ byte as u32) & 0xff) as usize] ^ (crc >> 8);
    }
    crc ^ 0xffffffff
}
`;

  return code;
}

/**
 * Generate geometry category classification
 * REMOVED: No longer generating geometry categories (unused code)
 */
function _generateGeometryCategories_removed(schema: ExpressSchema): string {
  let code = `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Auto-generated Geometry Category Classification
//!
//! Generated from EXPRESS schema: ${schema.name}
//!
//! DO NOT EDIT - This file is auto-generated by @ifc-lite/codegen

use super::IfcType;

/// Geometry representation categories
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GeometryCategory {
    /// Swept solids (extrusions, revolutions)
    SweptSolid,
    /// Boolean/CSG operations
    Boolean,
    /// Explicit mesh representations
    ExplicitMesh,
    /// Mapped/instanced geometry
    MappedItem,
    /// Surface models
    Surface,
    /// Curve geometry
    Curve,
    /// Other geometry types
    Other,
}

/// Profile definition categories
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProfileCategory {
    /// Parametric profiles (rectangle, circle, I-shape, etc.)
    Parametric,
    /// Arbitrary closed profiles
    Arbitrary,
    /// Composite profiles
    Composite,
}

impl IfcType {
    /// Get geometry category for this type
    pub fn geometry_category(&self) -> Option<GeometryCategory> {
        match self {
            // Swept solids
`;

  // Swept solids
  const sweptSolids = [
    'IfcExtrudedAreaSolid',
    'IfcExtrudedAreaSolidTapered',
    'IfcRevolvedAreaSolid',
    'IfcRevolvedAreaSolidTapered',
    'IfcSurfaceCurveSweptAreaSolid',
    'IfcFixedReferenceSweptAreaSolid',
    'IfcSweptDiskSolid',
    'IfcSweptDiskSolidPolygonal',
  ];
  for (const name of sweptSolids) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(GeometryCategory::SweptSolid),\n`;
    }
  }

  code += `
            // Boolean/CSG
`;

  // Boolean types
  const booleanTypes = [
    'IfcBooleanResult',
    'IfcBooleanClippingResult',
    'IfcCsgSolid',
    'IfcCsgPrimitive3D',
    'IfcBlock',
    'IfcSphere',
    'IfcRightCircularCone',
    'IfcRightCircularCylinder',
    'IfcRectangularPyramid',
  ];
  for (const name of booleanTypes) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(GeometryCategory::Boolean),\n`;
    }
  }

  code += `
            // Explicit mesh
`;

  // Explicit mesh types
  const meshTypes = [
    'IfcFacetedBrep',
    'IfcFacetedBrepWithVoids',
    'IfcAdvancedBrep',
    'IfcAdvancedBrepWithVoids',
    'IfcManifoldSolidBrep',
    'IfcTriangulatedFaceSet',
    'IfcPolygonalFaceSet',
    'IfcTriangulatedIrregularNetwork',
    'IfcTessellatedFaceSet',
    'IfcIndexedPolygonalFace',
    'IfcShellBasedSurfaceModel',
    'IfcFaceBasedSurfaceModel',
  ];
  for (const name of meshTypes) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(GeometryCategory::ExplicitMesh),\n`;
    }
  }

  code += `
            // Mapped items
`;

  if (schema.entities.find((e) => e.name === 'IfcMappedItem')) {
    code += `            Self::IfcMappedItem => Some(GeometryCategory::MappedItem),\n`;
  }

  code += `
            // Surfaces
`;

  const surfaceTypes = [
    'IfcBSplineSurface',
    'IfcBSplineSurfaceWithKnots',
    'IfcRationalBSplineSurfaceWithKnots',
    'IfcCylindricalSurface',
    'IfcSphericalSurface',
    'IfcToroidalSurface',
    'IfcPlane',
    'IfcCurveBoundedPlane',
    'IfcCurveBoundedSurface',
    'IfcRectangularTrimmedSurface',
    'IfcSurfaceOfLinearExtrusion',
    'IfcSurfaceOfRevolution',
  ];
  for (const name of surfaceTypes) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(GeometryCategory::Surface),\n`;
    }
  }

  code += `
            // Curves
`;

  const curveTypes = [
    'IfcBSplineCurve',
    'IfcBSplineCurveWithKnots',
    'IfcRationalBSplineCurveWithKnots',
    'IfcCompositeCurve',
    'IfcPolyline',
    'IfcTrimmedCurve',
    'IfcCircle',
    'IfcEllipse',
    'IfcLine',
    'IfcIndexedPolyCurve',
  ];
  for (const name of curveTypes) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(GeometryCategory::Curve),\n`;
    }
  }

  code += `
            _ => None,
        }
    }

    /// Get profile category for this type
    pub fn profile_category(&self) -> Option<ProfileCategory> {
        match self {
            // Parametric profiles
`;

  const parametricProfiles = [
    'IfcRectangleProfileDef',
    'IfcRectangleHollowProfileDef',
    'IfcRoundedRectangleProfileDef',
    'IfcCircleProfileDef',
    'IfcCircleHollowProfileDef',
    'IfcEllipseProfileDef',
    'IfcIShapeProfileDef',
    'IfcAsymmetricIShapeProfileDef',
    'IfcLShapeProfileDef',
    'IfcTShapeProfileDef',
    'IfcUShapeProfileDef',
    'IfcCShapeProfileDef',
    'IfcZShapeProfileDef',
    'IfcTrapeziumProfileDef',
  ];
  for (const name of parametricProfiles) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(ProfileCategory::Parametric),\n`;
    }
  }

  code += `
            // Arbitrary profiles
`;

  const arbitraryProfiles = [
    'IfcArbitraryClosedProfileDef',
    'IfcArbitraryProfileDefWithVoids',
    'IfcArbitraryOpenProfileDef',
    'IfcCenterLineProfileDef',
  ];
  for (const name of arbitraryProfiles) {
    if (schema.entities.find((e) => e.name === name)) {
      code += `            Self::${name} => Some(ProfileCategory::Arbitrary),\n`;
    }
  }

  code += `
            // Composite profiles
`;

  if (schema.entities.find((e) => e.name === 'IfcCompositeProfileDef')) {
    code += `            Self::IfcCompositeProfileDef => Some(ProfileCategory::Composite),\n`;
  }
  if (schema.entities.find((e) => e.name === 'IfcDerivedProfileDef')) {
    code += `            Self::IfcDerivedProfileDef => Some(ProfileCategory::Composite),\n`;
  }
  if (schema.entities.find((e) => e.name === 'IfcMirroredProfileDef')) {
    code += `            Self::IfcMirroredProfileDef => Some(ProfileCategory::Composite),\n`;
  }

  code += `
            _ => None,
        }
    }

    /// Check if this type is a spatial structure element
    pub fn is_spatial(&self) -> bool {
        matches!(
            self,
`;

  const spatialEntities = [
    'IfcProject',
    'IfcSite',
    'IfcBuilding',
    'IfcBuildingStorey',
    'IfcSpace',
    'IfcFacility',
    'IfcFacilityPart',
  ];
  const validSpatial = spatialEntities.filter((n) => schema.entities.find((e) => e.name === n));
  if (validSpatial.length > 0) {
    code += `            ${validSpatial.map((n) => `Self::${n}`).join('\n            | ')}\n`;
  } else {
    code += `            Self::Unknown(_) // No spatial types found\n`;
  }

  code += `        )
    }

    /// Check if this type can have geometry
    pub fn can_have_geometry(&self) -> bool {
        // Products can have geometry through representations
        self.is_product() && !self.is_spatial()
    }

    /// Check if this type is a product (can have placement/representation)
    pub fn is_product(&self) -> bool {
        // Check if it's a subtype of IfcProduct
        self.is_subtype_of(Self::IfcProduct) || *self == Self::IfcProduct
    }

    /// Check if this type is a relationship
    pub fn is_relationship(&self) -> bool {
        // Check if name starts with IfcRel
        self.name().starts_with("IfcRel")
    }

    /// Check if this is a building element
    pub fn is_building_element(&self) -> bool {
        let name = self.name();
        matches!(
            *self,
            Self::IfcWall | Self::IfcWallStandardCase | Self::IfcSlab |
            Self::IfcBeam | Self::IfcColumn | Self::IfcRoof |
            Self::IfcStair | Self::IfcRamp | Self::IfcRailing |
            Self::IfcPlate | Self::IfcMember | Self::IfcFooting |
            Self::IfcPile | Self::IfcCovering | Self::IfcCurtainWall |
            Self::IfcDoor | Self::IfcWindow | Self::IfcChimney |
            Self::IfcShadingDevice | Self::IfcBuildingElementProxy |
            Self::IfcBuildingElementPart
        ) || name.contains("Reinforc")
    }
}
`;

  return code;
}

/**
 * Categorize entities for organized output
 */
function categorizeEntities(
  schema: ExpressSchema
): Record<string, EntityDefinition[]> {
  const categories: Record<string, EntityDefinition[]> = {
    'Spatial Structure': [],
    'Building Elements': [],
    Openings: [],
    MEP: [],
    'Geometry Representations': [],
    'Geometry Primitives': [],
    Profiles: [],
    Curves: [],
    Surfaces: [],
    Relationships: [],
    Properties: [],
    Materials: [],
    'Presentation & Style': [],
    'Core & Common': [],
    Other: [],
  };

  for (const entity of schema.entities) {
    const name = entity.name;
    const chain = getInheritanceChain(entity, schema);

    if (
      name.includes('Site') ||
      name.includes('Building') ||
      name.includes('Storey') ||
      name.includes('Space') ||
      name.includes('Project') ||
      chain.includes('IfcSpatialStructureElement')
    ) {
      categories['Spatial Structure'].push(entity);
    } else if (
      chain.includes('IfcBuildingElement') ||
      name.includes('Wall') ||
      name.includes('Slab') ||
      name.includes('Beam') ||
      name.includes('Column')
    ) {
      categories['Building Elements'].push(entity);
    } else if (
      name.includes('Door') ||
      name.includes('Window') ||
      name.includes('Opening')
    ) {
      categories['Openings'].push(entity);
    } else if (
      name.includes('Pipe') ||
      name.includes('Duct') ||
      name.includes('Cable') ||
      chain.includes('IfcDistributionElement')
    ) {
      categories['MEP'].push(entity);
    } else if (
      name.includes('Representation') ||
      name.includes('Shape') ||
      name.includes('GeometricSet')
    ) {
      categories['Geometry Representations'].push(entity);
    } else if (
      name.includes('Solid') ||
      name.includes('Brep') ||
      name.includes('Boolean') ||
      name.includes('Csg') ||
      name.includes('FaceSet')
    ) {
      categories['Geometry Primitives'].push(entity);
    } else if (name.includes('Profile')) {
      categories['Profiles'].push(entity);
    } else if (
      name.includes('Curve') ||
      name.includes('Polyline') ||
      name.includes('Circle') ||
      name.includes('Ellipse') ||
      name.includes('Line') ||
      name.includes('Spline')
    ) {
      categories['Curves'].push(entity);
    } else if (name.includes('Surface') || name.includes('Plane')) {
      categories['Surfaces'].push(entity);
    } else if (name.startsWith('IfcRel')) {
      categories['Relationships'].push(entity);
    } else if (
      name.includes('Property') ||
      name.includes('Quantity') ||
      name.includes('Value')
    ) {
      categories['Properties'].push(entity);
    } else if (name.includes('Material')) {
      categories['Materials'].push(entity);
    } else if (
      name.includes('Style') ||
      name.includes('Colour') ||
      name.includes('Presentation')
    ) {
      categories['Presentation & Style'].push(entity);
    } else if (
      name.includes('Root') ||
      name.includes('Object') ||
      name.includes('Product') ||
      name.includes('Element') ||
      name.includes('Resource')
    ) {
      categories['Core & Common'].push(entity);
    } else {
      categories['Other'].push(entity);
    }
  }

  // Remove empty categories
  for (const key of Object.keys(categories)) {
    if (categories[key].length === 0) {
      delete categories[key];
    }
  }

  return categories;
}
