/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import { crc32 } from './crc32.js';
import type { EntityDefinition, ExpressSchema } from './express-parser.js';

/** Render the generated CRC32 constants without coupling this to enum emission. */
export function generateTypeIdConstants(
  schema: ExpressSchema,
  cratePrivate: boolean,
  categorize: (schema: ExpressSchema) => Record<string, EntityDefinition[]>,
): string {
  let code = `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Auto-generated IFC Type ID Constants
//!
//! CRC32 hashes for fast type identification.
//! Generated from EXPRESS schema: ${schema.name}
//!
//! DO NOT EDIT - This file is auto-generated by @ifc-lite/codegen

#![allow(dead_code)]

`;

  for (const [category, entities] of Object.entries(categorize(schema))) {
    code += `// ${category}\n`;
    for (const entity of entities) {
      code += `pub const ${entity.name.toUpperCase()}: u32 = ${crc32(entity.name)};\n`;
    }
    code += '\n';
  }

  return cratePrivate ? `${code.trimEnd()}\n` : code;
}
