#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# One-command wrapper for scripts/perf/browser-cold-ab.mts (#3978): builds a
# BASE viewer bundle in a throwaway git worktree, builds/reuses the BRANCH
# (working tree) bundle, and runs the interleaved cold-load A/B against both.
#
# DELIBERATELY MANUAL — see browser-cold-ab.mts's header. Not invoked by any
# workflow; `.github/workflows/benchmark.yml` is the separate, CI-wired,
# advisory-only sibling that only ever measures the working tree against a
# committed baseline.json, never a live base build.
#
# Usage:
#   scripts/perf/browser-cold-ab.sh                                  # public fixtures, self-comparison
#   scripts/perf/browser-cold-ab.sh --base origin/main --iters 5
#   scripts/perf/browser-cold-ab.sh --corpus scripts/perf/browser-corpus.local.json
#   scripts/perf/browser-cold-ab.sh --fixtures tests/models/ara3d/AC20-FZK-Haus.ifc
#
# Flags:
#   --base <ref>       git ref for "before" (default: self-comparison).
#                       An explicit ref requires a second
#                       `pnpm install` + viewer build in a throwaway worktree
#                       — the same cost `.github/workflows/benchmark.yml`
#                       already pays per PR, just run locally.
#   --iters <N>         interleaved rounds per fixture (default 5).
#   --corpus <path>      local, uncommitted manifest of private/large models
#                       (see browser-corpus.example.json). Never fetched or
#                       generated by this script — the files must already
#                       exist on disk.
#   --fixtures <a,b,…>  comma-separated repo-relative fixture paths (default:
#                       the two public CI fixtures, fetched via `pnpm fixtures`
#                       if missing).
#   --skip-branch-build reuse apps/viewer/dist as-is (you built it already).
#
# What this does NOT do: download or generate multi-GB fixtures, run in CI,
# or gate a PR. It prints a report and exits nonzero only on a harness fault
# (a sample that failed to load) — a "real change" verdict is informational.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

BASE_REF=""
ITERS=5
CORPUS=""
FIXTURES_CSV=""
SKIP_BRANCH_BUILD=0
EXTRA_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --base) BASE_REF="${2:?--base needs a ref}"; shift 2;;
    --iters) ITERS="${2:?--iters needs a number}"; shift 2;;
    --corpus) CORPUS="${2:?--corpus needs a path}"; shift 2;;
    --fixtures) FIXTURES_CSV="${2:?--fixtures needs a comma list}"; shift 2;;
    --skip-branch-build) SKIP_BRANCH_BUILD=1; shift;;
    -h|--help) sed -n '2,40p' "$0"; exit 0;;
    *) EXTRA_ARGS+=("$1"); shift;;
  esac
done

if [ -z "$FIXTURES_CSV" ]; then
  FIXTURES_CSV="tests/models/ara3d/AC20-FZK-Haus.ifc,tests/models/various/01_Snowdon_Towers_Sample_Structural(1).ifc"
  echo "browser-cold-ab.sh: no --fixtures given, defaulting to the two public CI fixtures" >&2
  node scripts/fixtures/fetch-fixtures.mjs "ara3d/AC20-FZK-Haus.ifc" "various/01_Snowdon_Towers_Sample_Structural(1).ifc" >&2
fi
IFS=',' read -r -a FIXTURES <<< "$FIXTURES_CSV"

# Source-based comparisons may not silently substitute a published engine.
build_source_viewer() {
  if ! command -v wasm-pack >/dev/null 2>&1 && [ ! -x "$HOME/.cargo/bin/wasm-pack" ]; then
    echo "browser-cold-ab.sh: wasm-pack required for ref-matched builds; supply frozen distributions to browser-cold-ab.mts instead." >&2
    return 2
  fi
  bash scripts/build-wasm.sh >&2
  local built_wasm_sha
  built_wasm_sha="$(node -p "require('crypto').createHash('sha256').update(require('fs').readFileSync('packages/wasm/pkg/ifc-lite_bg.wasm')).digest('hex')")"
  test -n "$built_wasm_sha"
  pnpm turbo build --filter=@ifc-lite/viewer >&2
  if [ "$built_wasm_sha" != "$(node -p "require('crypto').createHash('sha256').update(require('fs').readFileSync('packages/wasm/pkg/ifc-lite_bg.wasm')).digest('hex')")" ]; then
    echo "browser-cold-ab.sh: WASM changed after the source build; refusing mismatched artifacts" >&2
    return 2
  fi
  local served_wasm_sha
  served_wasm_sha="$(node -p "const fs=require('fs');const dir='apps/viewer/dist/assets/';const names=fs.readdirSync(dir).filter(n=>/^ifc-lite_bg-.*\\.wasm$/.test(n));if(names.length!==1)throw Error('expected one viewer IFC WASM asset');require('crypto').createHash('sha256').update(fs.readFileSync(dir+names[0])).digest('hex')")"
  if [ "$built_wasm_sha" != "$served_wasm_sha" ]; then
    echo "browser-cold-ab.sh: served viewer WASM differs from source-built engine" >&2
    return 2
  fi
  echo "browser-cold-ab.sh: source-built and served WASM SHA256 $built_wasm_sha" >&2
}

# --- Branch (working tree) build --------------------------------------------
if [ "$SKIP_BRANCH_BUILD" -eq 0 ]; then
  echo "browser-cold-ab.sh: building branch viewer bundle (working tree)…" >&2
  build_source_viewer
fi
if [ ! -d apps/viewer/dist ]; then
  echo "browser-cold-ab.sh: apps/viewer/dist missing after build — aborting." >&2
  exit 1
fi

CMD_ARGS=("${FIXTURES[@]}" --dist-branch apps/viewer/dist --iters "$ITERS")
[ -n "$CORPUS" ] && CMD_ARGS+=(--corpus "$CORPUS")
if [ "${#EXTRA_ARGS[@]}" -gt 0 ]; then
  CMD_ARGS+=("${EXTRA_ARGS[@]}")
fi

# --- Base build in a throwaway worktree (only if --base was requested) ------
# Self-mode (no --base) is a first-class use, not a fallback: it is exactly
# what a repeatability check or a --fault-inject-ms harness self-test wants,
# and it skips the second install+build entirely.
if [ -n "$BASE_REF" ]; then
  BASE_SHA="$(git rev-parse "$BASE_REF")"
  echo "browser-cold-ab.sh: base=$BASE_SHA ($BASE_REF)  branch=$(git rev-parse --short HEAD)" >&2

  TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/ifc-browser-ab.XXXXXX")"
  BASE_WT="$TMP_ROOT/base-wt"
  cleanup() {
    git worktree remove --force "$BASE_WT" >/dev/null 2>&1 || true
    rm -rf "$TMP_ROOT" >/dev/null 2>&1 || true
  }
  trap cleanup EXIT

  echo "browser-cold-ab.sh: building base viewer bundle @ $BASE_SHA in a throwaway worktree…" >&2
  git worktree add --detach "$BASE_WT" "$BASE_SHA" >&2
  (
    cd "$BASE_WT"
    pnpm install --frozen-lockfile >&2
    build_source_viewer
  )
  if [ ! -d "$BASE_WT/apps/viewer/dist" ]; then
    echo "browser-cold-ab.sh: base build produced no apps/viewer/dist — aborting." >&2
    exit 1
  fi
  BRANCH_LABEL="$(git rev-parse HEAD)"
  if [ "$SKIP_BRANCH_BUILD" -eq 1 ]; then
    BRANCH_LABEL="supplied-branch-dist"
  elif [ -n "$(git status --porcelain)" ]; then
    BRANCH_LABEL="${BRANCH_LABEL}-dirty"
  fi
  CMD_ARGS+=(--dist-base "$BASE_WT/apps/viewer/dist" --base-label "$BASE_SHA" --branch-label "$BRANCH_LABEL")
else
  echo "browser-cold-ab.sh: no --base and no origin/main — running self-mode (repeatability only, no base build)." >&2
fi

status=0
npx tsx scripts/perf/browser-cold-ab.mts "${CMD_ARGS[@]}" || status=$?
exit "$status"
